repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
      files: .*\.*.py
    - id: trailing-whitespace
      files: .*\.*.py
    - id: debug-statements
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: requirements-txt-fixer
      args:
        - requirements.txt
        - requirements-dev.txt

- repo: repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "0.12.1"
  hooks:
    - id: pyproject-fmt

# flake8 pep checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.0.1
  hooks:
  - id: flake8
    args: # arguments to configure flake8
      - "--max-line-length=100"
      # These folders will be excluded
      - "--exclude=docs,.git,__pycache__,dist"
      - "--ignore=E265,E501,E221,E251,E203,E201,E124,E202,E241,E251,W293,W291"
