repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
      files: .*\.*.py
    - id: trailing-whitespace
      files: .*\.*.py
    - id: debug-statements
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: requirements-txt-fixer
      args:
        - requirements.txt
        - requirements-dev.txt

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.5
  hooks:
    - id: ruff

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "2.1.3"
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
  hooks:
    - id: pyupgrade
      args: [--py38-plus]
