name: Build and Deploy docs

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 --file requirements.txt --file requirements-dev.txt --file docs/requirements.txt --channel conda-forge

    - name: Install pocean-core
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        pushd docs
        sphinx-apidoc -M -f -o api ../pocean ../pocean/tests
        make clean html linkcheck
        popd

    - name: Deploy
      if: success() && github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site/html
